rss:
  - https://feeds.bbci.co.uk/news/odd/rss.xml
  - https://www.huffpost.com/section/weird-news/feed
  - https://feeds.skynews.com/feeds/rss/strange.xml
  - https://www.reddit.com/r/nottheonion/.rss
  - https://www.upi.com/Science_News/Strange_News/rss/
