rss:
  # Major odd/strange sections
  - https://feeds.bbci.co.uk/news/odd/rss.xml
  - https://www.huffpost.com/section/weird-news/feed
  - https://feeds.skynews.com/feeds/rss/strange.xml
  - https://www.upi.com/Science_News/Strange_News/rss/
  - https://www.npr.org/rss/rss.php?id=1019          # NPR "Strange News"
  - https://boingboing.net/feed                     # Boing Boing (quirky/odd)
  - https://www.atlasobscura.com/rss                # Atlas Obscura stories

  # Reddit (odd headlines; we’ll use summary, not scrape)
  - https://www.reddit.com/r/nottheonion/.rss
  - https://www.reddit.com/r/WTF/.rss
  - https://www.reddit.com/r/oddlyterrifying/.rss
